// TWENDE Kazi v2 — Mock Data
// Sprint 08: Gig Worker Platform SDK

import type {
  WorkerProfile,
  Gig,
  GigApplication,
  GigReview,
  EarningsSummary,
} from './types';

// ─── WORKER PROFILES ─────────────────────────────────────────────────────

export const workerProfiles: WorkerProfile[] = [
  {
    id: 'worker-001',
    userId: 'u1',
    name: 'Wanjiku M.',
    avatar: 'WM',
    bio: 'Reliable driver with 5+ years experience. Safe, punctual, and friendly. Available for deliveries, rides, and courier services.',
    yearsExperience: 5,
    hourlyRate: 250,
    dailyRate: 1800,
    languages: ['Swahili', 'English'],
    skills: [
      { category: 'driving', subcategory: 'motorcycle', isVerified: true, yearsExperience: 5 },
      { category: 'delivery', isVerified: true, yearsExperience: 3 },
      { category: 'courier', isVerified: false, yearsExperience: 1 },
    ],
    serviceAreas: ['Kawangware', 'Kibera', 'Ngong Road', 'Karen'],
    availability: [
      { day: 'Mon', slots: ['08:00-18:00'] },
      { day: 'Tue', slots: ['08:00-18:00'] },
      { day: 'Wed', slots: ['08:00-18:00'] },
      { day: 'Thu', slots: ['08:00-18:00'] },
      { day: 'Fri', slots: ['08:00-18:00'] },
      { day: 'Sat', slots: ['09:00-14:00'] },
    ],
    isVerified: true,
    idVerified: true,
    skillsTested: true,
    totalGigsCompleted: 124,
    totalEarnings: 456000,
    averageRating: 4.8,
    responseRate: 92,
    portfolioPhotos: [],
    location: { lat: -1.2921, lng: 36.8219, ward: 'Kawangware' },
  },
  {
    id: 'worker-002',
    userId: 'u2',
    name: 'Juma K.',
    avatar: 'JK',
    bio: 'Experienced plumber and electrician. Residential and commercial work. Available for emergency repairs.',
    yearsExperience: 8,
    hourlyRate: 400,
    dailyRate: 2800,
    languages: ['Swahili', 'English'],
    skills: [
      { category: 'plumbing', subcategory: 'residential', isVerified: true, yearsExperience: 8 },
      { category: 'electrical', subcategory: 'residential', isVerified: true, yearsExperience: 5 },
      { category: 'carpentry', isVerified: false, yearsExperience: 2 },
    ],
    serviceAreas: ['CBD', 'Ngara', 'Eastleigh', 'Parklands'],
    availability: [
      { day: 'Mon', slots: ['08:00-17:00'] },
      { day: 'Tue', slots: ['08:00-17:00'] },
      { day: 'Wed', slots: ['08:00-17:00'] },
      { day: 'Thu', slots: ['08:00-17:00'] },
      { day: 'Fri', slots: ['08:00-17:00'] },
      { day: 'Sat', slots: ['09:00-15:00'] },
    ],
    isVerified: true,
    idVerified: true,
    skillsTested: true,
    totalGigsCompleted: 89,
    totalEarnings: 312000,
    averageRating: 4.6,
    responseRate: 85,
    portfolioPhotos: [],
    location: { lat: -1.2845, lng: 36.8234, ward: 'CBD' },
  },
  {
    id: 'worker-003',
    userId: 'u3',
    name: 'Achieng O.',
    avatar: 'AO',
    bio: 'Professional cleaner with attention to detail. Deep cleaning, office cleaning, and move-out cleaning services.',
    yearsExperience: 4,
    hourlyRate: 200,
    dailyRate: 1200,
    languages: ['Swahili', 'English', 'Luo'],
    skills: [
      { category: 'cleaning', subcategory: 'residential', isVerified: true, yearsExperience: 4 },
      { category: 'cleaning', subcategory: 'commercial', isVerified: true, yearsExperience: 2 },
    ],
    serviceAreas: ['Kawangware', 'Kibera', 'Karen', 'Langata'],
    availability: [
      { day: 'Mon', slots: ['07:00-16:00'] },
      { day: 'Tue', slots: ['07:00-16:00'] },
      { day: 'Wed', slots: ['07:00-16:00'] },
      { day: 'Thu', slots: ['07:00-16:00'] },
      { day: 'Fri', slots: ['07:00-16:00'] },
      { day: 'Sat', slots: ['08:00-14:00'] },
      { day: 'Sun', slots: ['10:00-14:00'] },
    ],
    isVerified: true,
    idVerified: true,
    skillsTested: true,
    totalGigsCompleted: 156,
    totalEarnings: 189000,
    averageRating: 4.9,
    responseRate: 96,
    portfolioPhotos: [],
    location: { lat: -1.295, lng: 36.815, ward: 'Kibera' },
  },
  {
    id: 'worker-004',
    userId: 'u4',
    name: 'Peter N.',
    avatar: 'PN',
    bio: 'Skilled construction worker. Masonry, painting, and general labor. Hardworking and reliable.',
    yearsExperience: 6,
    hourlyRate: 300,
    dailyRate: 2000,
    languages: ['Swahili'],
    skills: [
      { category: 'construction', subcategory: 'masonry', isVerified: false, yearsExperience: 6 },
      { category: 'painting', isVerified: false, yearsExperience: 3 },
      { category: 'general_labor', isVerified: false, yearsExperience: 6 },
    ],
    serviceAreas: ['Gikomba', 'Eastleigh', 'CBD'],
    availability: [
      { day: 'Mon', slots: ['06:00-18:00'] },
      { day: 'Tue', slots: ['06:00-18:00'] },
      { day: 'Wed', slots: ['06:00-18:00'] },
      { day: 'Thu', slots: ['06:00-18:00'] },
      { day: 'Fri', slots: ['06:00-18:00'] },
      { day: 'Sat', slots: ['06:00-14:00'] },
    ],
    isVerified: false,
    idVerified: false,
    skillsTested: false,
    totalGigsCompleted: 42,
    totalEarnings: 98000,
    averageRating: 4.2,
    responseRate: 70,
    portfolioPhotos: [],
    location: { lat: -1.2867, lng: 36.8421, ward: 'Gikomba' },
  },
];

// ─── GIGS ──────────────────────────────────────────────────────────────────

export const gigs: Gig[] = [
  {
    id: 'gig-001',
    employerId: 'emp-001',
    employerName: 'Mama Nuru\'s Boutique',
    title: 'Delivery Driver — Daily Package Runs',
    description: 'Need a reliable motorcycle driver to deliver packages to customers in Kawangware, Kibera, and Ngong Road areas. 6-8 deliveries per day. Must have own bike.',
    requiredSkills: ['driving', 'delivery'],
    location: { lat: -1.2921, lng: 36.8219, address: 'Kawangware Market, Stall 45', ward: 'Kawangware' },
    scheduledDate: '2026-07-07',
    startTime: '08:00',
    endTime: '16:00',
    durationHours: 8,
    budgetType: 'fixed',
    budgetAmount: 1500,
    status: 'published',
    requiresVerifiedWorker: true,
    isUrgent: false,
    riskCategory: 'medium',
    viewCount: 34,
    applicationCount: 5,
    createdAt: '2026-07-03T10:00:00Z',
  },
  {
    id: 'gig-002',
    employerId: 'emp-002',
    employerName: 'Nairobi Apartments Ltd',
    title: 'Emergency Plumbing Repair',
    description: 'Leaking pipe in bathroom needs immediate repair. Tools provided. Estimated 2-3 hours work.',
    requiredSkills: ['plumbing'],
    location: { lat: -1.2845, lng: 36.8234, address: 'Ngara Road, Block C', ward: 'Ngara' },
    scheduledDate: '2026-07-06',
    startTime: '14:00',
    endTime: '17:00',
    durationHours: 3,
    budgetType: 'fixed',
    budgetAmount: 2500,
    status: 'published',
    requiresVerifiedWorker: false,
    isUrgent: true,
    riskCategory: 'low',
    viewCount: 28,
    applicationCount: 3,
    createdAt: '2026-07-03T08:30:00Z',
  },
  {
    id: 'gig-003',
    employerId: 'emp-003',
    employerName: 'Sunshine School',
    title: 'Weekly Office Cleaning',
    description: 'Clean 4 classrooms and 2 offices every Saturday. Cleaning supplies provided. 4 hours per session.',
    requiredSkills: ['cleaning'],
    location: { lat: -1.295, lng: 36.815, address: 'Kibera Drive, Building 12', ward: 'Kibera' },
    scheduledDate: '2026-07-12',
    startTime: '08:00',
    endTime: '12:00',
    durationHours: 4,
    budgetType: 'hourly',
    budgetAmount: 250,
    status: 'published',
    requiresVerifiedWorker: true,
    isUrgent: false,
    riskCategory: 'low',
    viewCount: 45,
    applicationCount: 8,
    createdAt: '2026-07-02T16:00:00Z',
  },
  {
    id: 'gig-004',
    employerId: 'emp-004',
    employerName: 'Juma Construction',
    title: 'Construction Helper — 2 Week Project',
    description: 'General labor for building site. Carrying materials, mixing cement, assisting masons. 8 hours/day, Monday-Saturday.',
    requiredSkills: ['construction', 'general_labor'],
    location: { lat: -1.2867, lng: 36.8421, address: 'Gikomba Market Area', ward: 'Gikomba' },
    scheduledDate: '2026-07-14',
    startTime: '07:00',
    endTime: '15:00',
    durationHours: 8,
    budgetType: 'fixed',
    budgetAmount: 1800,
    status: 'published',
    requiresVerifiedWorker: false,
    isUrgent: false,
    riskCategory: 'high',
    viewCount: 19,
    applicationCount: 2,
    createdAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'gig-005',
    employerId: 'emp-005',
    employerName: 'TechFix Electronics',
    title: 'Shop Renovation — Electrical Work',
    description: 'Rewire shop lighting and install new outlets. Must be certified electrician. Tools and materials provided.',
    requiredSkills: ['electrical'],
    location: { lat: -1.2845, lng: 36.8234, address: 'Luthuli Avenue, Shop 12', ward: 'CBD' },
    scheduledDate: '2026-07-10',
    startTime: '09:00',
    endTime: '17:00',
    durationHours: 8,
    budgetType: 'fixed',
    budgetAmount: 5000,
    status: 'published',
    requiresVerifiedWorker: true,
    isUrgent: false,
    riskCategory: 'medium',
    viewCount: 22,
    applicationCount: 4,
    createdAt: '2026-07-03T11:00:00Z',
  },
  {
    id: 'gig-006',
    employerId: 'emp-001',
    employerName: 'Mama Nuru\'s Boutique',
    title: 'Weekend Courier — Karen Deliveries',
    description: 'Deliver fashion orders to Karen and Ngong Road area. 4-5 deliveries. Saturday only.',
    requiredSkills: ['driving', 'courier'],
    location: { lat: -1.2921, lng: 36.8219, address: 'Kawangware Market, Stall 45', ward: 'Kawangware' },
    scheduledDate: '2026-07-12',
    startTime: '10:00',
    endTime: '14:00',
    durationHours: 4,
    budgetType: 'fixed',
    budgetAmount: 1200,
    status: 'published',
    requiresVerifiedWorker: false,
    isUrgent: false,
    riskCategory: 'medium',
    viewCount: 15,
    applicationCount: 2,
    createdAt: '2026-07-03T14:00:00Z',
  },
];

// ─── APPLICATIONS ──────────────────────────────────────────────────────────

export const gigApplications: GigApplication[] = [
  {
    id: 'app-001',
    gigId: 'gig-001',
    workerId: 'worker-001',
    workerName: 'Wanjiku M.',
    coverNote: 'I have 5 years experience as a delivery driver in Kawangware. I know all the routes well.',
    proposedRate: 1500,
    status: 'pending',
    matchScore: 95,
    createdAt: '2026-07-03T12:00:00Z',
  },
  {
    id: 'app-002',
    gigId: 'gig-001',
    workerId: 'worker-004',
    workerName: 'Peter N.',
    coverNote: 'I can do this. I have a motorcycle.',
    status: 'pending',
    matchScore: 62,
    createdAt: '2026-07-03T13:00:00Z',
  },
  {
    id: 'app-003',
    gigId: 'gig-002',
    workerId: 'worker-002',
    workerName: 'Juma K.',
    coverNote: 'Certified plumber. I can fix this today. Available immediately.',
    proposedRate: 2500,
    status: 'pending',
    matchScore: 98,
    createdAt: '2026-07-03T09:00:00Z',
  },
  {
    id: 'app-004',
    gigId: 'gig-003',
    workerId: 'worker-003',
    workerName: 'Achieng O.',
    coverNote: 'I have 4 years cleaning experience. I bring my own supplies if needed.',
    proposedRate: 250,
    status: 'pending',
    matchScore: 92,
    createdAt: '2026-07-02T18:00:00Z',
  },
];

// ─── REVIEWS ─────────────────────────────────────────────────────────────

export const gigReviews: GigReview[] = [
  {
    id: 'review-001',
    gigId: 'gig-001',
    reviewerId: 'emp-001',
    reviewerName: 'Mama Nuru',
    revieweeId: 'worker-001',
    revieweeName: 'Wanjiku M.',
    overallRating: 5,
    punctualityRating: 5,
    qualityRating: 5,
    communicationRating: 4,
    reviewText: 'Wanjiku was excellent! All deliveries made on time, customers were happy. Will hire again.',
    isDisputed: false,
    createdAt: '2026-06-28T10:00:00Z',
  },
  {
    id: 'review-002',
    gigId: 'gig-002',
    reviewerId: 'emp-002',
    reviewerName: 'Nairobi Apartments',
    revieweeId: 'worker-002',
    revieweeName: 'Juma K.',
    overallRating: 4,
    punctualityRating: 5,
    qualityRating: 4,
    communicationRating: 4,
    reviewText: 'Fixed the leak quickly. Professional work. Slightly messy cleanup but overall good.',
    isDisputed: false,
    createdAt: '2026-06-25T14:00:00Z',
  },
  {
    id: 'review-003',
    gigId: 'gig-003',
    reviewerId: 'emp-003',
    reviewerName: 'Sunshine School',
    revieweeId: 'worker-003',
    revieweeName: 'Achieng O.',
    overallRating: 5,
    punctualityRating: 5,
    qualityRating: 5,
    communicationRating: 5,
    reviewText: 'Achieng is amazing! The classrooms have never been cleaner. Highly recommend.',
    isDisputed: false,
    createdAt: '2026-06-20T09:00:00Z',
  },
];

// ─── EARNINGS ─────────────────────────────────────────────────────────────

export const weeklyEarnings: EarningsSummary = {
  period: 'weekly',
  total: 18500,
  platformFees: 925,
  insurancePremiums: 300,
  netEarnings: 17275,
  gigCount: 8,
  data: [
    { label: 'Mon', earnings: 2800, gigs: 2 },
    { label: 'Tue', earnings: 3200, gigs: 2 },
    { label: 'Wed', earnings: 2600, gigs: 1 },
    { label: 'Thu', earnings: 3500, gigs: 2 },
    { label: 'Fri', earnings: 3100, gigs: 1 },
    { label: 'Sat', earnings: 1900, gigs: 0 },
    { label: 'Sun', earnings: 1400, gigs: 0 },
  ],
};

export const monthlyEarnings: EarningsSummary = {
  period: 'monthly',
  total: 74000,
  platformFees: 3700,
  insurancePremiums: 1200,
  netEarnings: 69100,
  gigCount: 32,
  data: [
    { label: 'Week 1', earnings: 18500, gigs: 8 },
    { label: 'Week 2', earnings: 19200, gigs: 9 },
    { label: 'Week 3', earnings: 17800, gigs: 7 },
    { label: 'Week 4', earnings: 18500, gigs: 8 },
  ],
};

// ─── SKILL CATEGORIES ──────────────────────────────────────────────────────

export const skillCategories = [
  { id: 'driving', name: 'Driving', icon: 'bike' },
  { id: 'delivery', name: 'Delivery', icon: 'package' },
  { id: 'plumbing', name: 'Plumbing', icon: 'wrench' },
  { id: 'electrical', name: 'Electrical', icon: 'zap' },
  { id: 'cleaning', name: 'Cleaning', icon: 'sparkles' },
  { id: 'construction', name: 'Construction', icon: 'hammer' },
  { id: 'carpentry', name: 'Carpentry', icon: 'tree' },
  { id: 'painting', name: 'Painting', icon: 'paint' },
  { id: 'courier', name: 'Courier', icon: 'truck' },
  { id: 'general_labor', name: 'General Labor', icon: 'hardhat' },
];

// ─── CURRENT USER WORKER PROFILE (for demo) ─────────────────────────────

export const currentWorkerProfile = workerProfiles[0];
