"""add country fields

Revision ID: 4d6d1282b87f
Revises: e6671ba47247
Create Date: 2026-08-13 21:08:00.690855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6d1282b87f'
down_revision: Union[str, Sequence[str], None] = 'e6671ba47247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=2), nullable=False, server_default='TZ'))
    op.add_column('groups', sa.Column('country', sa.String(length=2), nullable=False, server_default='TZ'))
    op.add_column('members', sa.Column('country', sa.String(length=2), nullable=False, server_default='TZ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'country')
    op.drop_column('groups', 'country')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
