"""add kyc tiers and identity attestations

Revision ID: 8c900e490d7b
Revises: c1a7d3f90b52
Create Date: 2026-09-08 07:33:27.338325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c900e490d7b'
down_revision: Union[str, Sequence[str], None] = 'c1a7d3f90b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_attestations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('officer_name', sa.String(length=120), nullable=False),
    sa.Column('officer_title', sa.String(length=60), nullable=False),
    sa.Column('office', sa.String(length=120), nullable=False),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('letter_reference', sa.String(length=100), nullable=True),
    sa.Column('letter_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('attesting_officers', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_attestations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_attestations_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_tier', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('kyc_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('kyc_reverify_after', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

    # Backfill: members already holding a national_id have, in substance, reached
    # Tier 2 by the registry route. Without this they drop to Tier 0 on deploy and
    # silently lose borrowing rights they already had.
    op.execute(
        sa.text(
            "UPDATE members SET kyc_tier = 2, kyc_method = 'registry', "
            "kyc_verified_at = CURRENT_TIMESTAMP "
            "WHERE national_id IS NOT NULL AND national_id <> ''"
        )
    )
    # Everyone else starts at Tier 0 and can still join a group and contribute.
    op.execute(sa.text("UPDATE members SET kyc_tier = 0 WHERE kyc_tier IS NULL"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('kyc_reverify_after')
        batch_op.drop_column('kyc_verified_at')
        batch_op.drop_column('kyc_method')
        batch_op.drop_column('kyc_tier')

    with op.batch_alter_table('identity_attestations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_attestations_member_id'))

    op.drop_table('identity_attestations')
    # ### end Alembic commands ###
