"""add transactions table and loan_balance

Revision ID: bf94de766136
Revises: a92e50151839
Create Date: 2026-08-27 07:59:44.823843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf94de766136'
down_revision: Union[str, Sequence[str], None] = 'a92e50151839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('mpesa_receipt', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_group_id'), 'transactions', ['group_id'], unique=False)
    op.create_index(op.f('ix_transactions_loan_id'), 'transactions', ['loan_id'], unique=False)
    op.create_index(op.f('ix_transactions_member_id'), 'transactions', ['member_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # server_default so the NOT NULL add succeeds against tables that already
    # hold loan rows; existing loans start with a zero outstanding balance.
    op.add_column(
        'loan_applications',
        sa.Column(
            'loan_balance',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0.00',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'loan_balance')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_member_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_loan_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_group_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
