"""add rbac roles

Revision ID: e6671ba47247
Revises: 2938610c7b43
Create Date: 2026-08-13 20:58:21.807404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6671ba47247'
down_revision: Union[str, Sequence[str], None] = '2938610c7b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('role', sa.String(length=20), nullable=False, server_default='member'))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('members', 'role')
    # ### end Alembic commands ###
